### PR TITLE
add panel AnyWidgetComponent

### PR DESCRIPTION
**Pull request by Jhsmit**
Adding panel's AnyWidgetComponent

Should this be called a `Pane`? `Widget`? Something else?
Currently its a `PDBeMolstarPane`

There is an error:
Uncaught (in promise) TypeError: window.PDBeMolstarPlugin is not a constructor

probably because of how I import the PDBeMolstarPlugin 
https://github.com/Jhsmit/ipymolstar/blob/acd549bf4df5bab7dac2990f95061ce6e801cb3e/src/ipymolstar/widget.js#L137

At the time I could not get the importing to work any other way but now there are some upstream changes and it might be worth taking another look at bundling: https://anywidget.dev/en/bundling/

### CODE REVIEW

**Comment by philippjfr** [comment]
I had this working somewhere. Will see if I can dig it up tomorrow, if I forget please ping me.

**Comment by MarcSkovMadsen** [comment]
I would recommend calling the module `panel` in instead of `pane`. That makes it more discoverable that you are supporting panel framework. And it would also extend to other frameworks adopting to [AFM specification](https://anywidget.dev/en/afm/).

I would recommend keeping  the name of the component as aligned to the AnyWidget/ Jupyter one as possible. I.e. without the `Pane` suffix.

**Comment by Jhsmit** [comment]
I thought naming the module `panel` same as the package `panel` would give problems but seems like it works. I have now named it the same so then if you want the AnyWidget version

`from ipymolstar import PDBeMolstar`

and for the panel component

`from ipymolstar.panel import PDBeMolstar`

**Comment by MarcSkovMadsen** [comment]
If you change `import * as myModule from "https://cdn.jsdelivr.net/npm/pdbe-molstar@3.2.0/build/pdbe-molstar-plugin.js"` to `import "https://cdn.jsdelivr.net/npm/pdbe-molstar@3.2.0/build/pdbe-molstar-plugin.js";` then `TypeError: window.PDBeMolstarPlugin is not a constructor` will go away. And other exceptions will be raised because you've now declared all the relevant parameters yet.

**Comment by MarcSkovMadsen** [comment]
To make this general you should refactor `class PDBeMolstar(anywidget.AnyWidget):` into two classes

`class PDBeMolstarBase():`. This class contains all the attributes and methods that does not refer to `anywidget.AnyWidget` or `traitlets`.

`class PDBeMolstar(PDBeMolstarBase, anywidget.AnyWidget)`. This class adds the traitlets.

The the Panel class will be `class PDBeMolstar(PDBeMolstarBase, pn.custom.AnyWidgetComponent)`.

**Comment by Jhsmit** [comment]
This now mostly works, I've reproduced the solara app as a panel example. I'll probably merge this and make a new release later today so that its out. 

Its been a while since I wrote a panel app, but together with Clause I could get it working very quickly, so that was a nice experience :)

Only the mouseover hover doesnt work, if there is a fix for that it would be nice to add. This is the expected behavior:
image

**Comment by MarcSkovMadsen** [comment]
@philippjfr . What is the trick to get mouse events working inside shadow dom?

**Comment by philippjfr** [comment]
Sadly this is highly dependent on the specific library so there's not one magic "trick". Will have to take a look.

**Comment by MarcSkovMadsen** [comment]
Congrats @Jhsmit 🚀

**Pull request merged**
